import {describe,expect,it} from 'vitest';
import {localizedCacheKey,resolveLocalizedEntity,translationCoverage} from './localized-content';
const base={slug:'black-banner-company',name:'The Black Banner Company',description:'Veteranos sob o mesmo estandarte.',count:10,status:'Em desenvolvimento',translations:{en:{status:'published' as const,version:2,fields:{name:'The Black Banner Company',description:'Veterans under the same banner.'}},es:{status:'draft' as const,version:1,fields:{name:'La CompaÃ±Ã­a del Estandarte Negro',description:'Veteranos bajo el mismo estandarte.'}}}};
describe('resolveLocalizedEntity',()=>{
  it('resolve traduÃ§Ã£o publicada e completa sem misturar o original',()=>{const result=resolveLocalizedEntity('collections',base,'en');expect(result.data).toMatchObject({description:'Veterans under the same banner.',count:10});expect(result).toMatchObject({requestedLocale:'en',resolvedLocale:'en',usedFallback:false,translationStatus:'published'});expect(result.data).not.toHaveProperty('translations')});
  it('aplica fallback integral para rascunho',()=>{const result=resolveLocalizedEntity('collections',base,'es');expect(result.data.description).toBe(base.description);expect(result).toMatchObject({resolvedLocale:'pt-br',usedFallback:true,translationStatus:'draft'})});
  it('aplica fallback integral para traduÃ§Ã£o ausente',()=>{const result=resolveLocalizedEntity('collections',{...base,translations:{}},'en');expect(result).toMatchObject({resolvedLocale:'pt-br',usedFallback:true,translationStatus:'missing'})});
  it('recusa traduÃ§Ã£o publicada parcial',()=>{const partial={...base,translations:{es:{status:'published' as const,fields:{name:'La CompaÃ±Ã­a'}}}};const result=resolveLocalizedEntity('collections',partial,'es');expect(result.data.description).toBe(base.description);expect(result.translationStatus).toBe('incomplete');expect(translationCoverage('collections',partial,'es').missingFields).toContain('description')});
  it('inclui locale na chave de cache',()=>{expect(localizedCacheKey('collections','es',base.slug)).toBe('collections:es:black-banner-company');expect(localizedCacheKey('collections','en',base.slug)).not.toBe(localizedCacheKey('collections','es',base.slug))});
});
