-- Prisma's uuid() defaults are generated by the client. Remove database defaults
-- left by earlier migrations so the live Preview schema matches schema.prisma.
ALTER TABLE "WorldEntity" ALTER COLUMN "canonicalId" DROP DEFAULT;
ALTER TABLE "SemanticRelationVersion" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "CanonVersion" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "CanonSnapshot" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "ChangeSet" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "RestoreOperation" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "MediaVariant" ALTER COLUMN "id" DROP DEFAULT;
