import Link from 'next/link';
import {ExternalLink,Star} from 'lucide-react';
import type {Currency,ListingBadge,ListingStatus,Marketplace,MarketplaceListing} from '@/types/marketplace';

const statusLabel:Record<ListingStatus,string>={'coming-soon':'Coming Soon','in-production':'In Production',available:'Available','early-access':'Early Access',exclusive:'Exclusive',retired:'Retired',archived:'Archived'};
const badgeLabel:Record<ListingBadge,string>={new:'New','best-seller':'Best Seller',popular:'Popular',featured:'Featured',exclusive:'Exclusive','coming-soon':'Coming Soon'};
export function PriceTag({price,currency}:{price:number;currency:Currency}){return <strong className="market-price">{new Intl.NumberFormat('pt-BR',{style:'currency',currency}).format(price)}</strong>}
export function AvailabilityBadge({status}:{status:ListingStatus}){return <span className={`availability-badge status-${status}`}>{statusLabel[status]}</span>}
export function MarketplaceBadge({badge}:{badge:ListingBadge}){return <span className="market-badge">{badgeLabel[badge]}</span>}
export function MarketplaceButton({url,label='Comprar agora'}:{url:string;label?:string}){return <a className="button" href={url} target="_blank" rel="noopener noreferrer">{label}<ExternalLink size={15}/></a>}
export function MarketplaceCard({listing,marketplace}:{listing:MarketplaceListing;marketplace:Marketplace}){return <article className="market-card" style={{'--market-color':marketplace.primaryColor} as React.CSSProperties}><div className="market-card-head"><span className="market-logo" aria-hidden>{marketplace.name.slice(0,2).toUpperCase()}</span><div><small>DOWNLOAD STL</small><h3 className="serif">{marketplace.name}</h3></div><AvailabilityBadge status={listing.status}/></div><h4>{listing.title}</h4><div className="market-badges">{listing.badges.map(badge=><MarketplaceBadge badge={badge} key={badge}/>)}</div><PriceTag price={listing.price} currency={listing.currency}/>{listing.rating&&<span className="market-rating" aria-label={`${listing.rating} de 5 estrelas`}><Star size={14} fill="currentColor"/> {listing.rating.toFixed(1)}</span>}<p className="muted">{listing.notes||listing.license}</p><MarketplaceButton url={listing.url} label={listing.status==='available'||listing.status==='early-access'?'Comprar agora':'Ver detalhes'}/></article>}
export function MarketplaceGrid({listings,marketplaces}:{listings:MarketplaceListing[];marketplaces:Marketplace[]}){return <div className="market-grid">{listings.map(listing=>{const market=marketplaces.find(item=>item.id===listing.marketplaceId);return market?<MarketplaceCard key={listing.id} listing={listing} marketplace={market}/>:null})}</div>}
export function MarketplaceList(props:{listings:MarketplaceListing[];marketplaces:Marketplace[]}){return <MarketplaceGrid {...props}/>}
export function MarketplaceHero({title,status='available'}:{title:string;status?:ListingStatus}){return <header className="marketplace-hero"><span className="eyebrow">Marketplace Hub</span><h1 className="serif">{title}</h1><AvailabilityBadge status={status}/></header>}
export function MarketplaceDirectoryCard({marketplace,count}:{marketplace:Marketplace;count:number}){return <Link className="market-directory-card" href={`/marketplaces/${marketplace.slug}`} style={{'--market-color':marketplace.primaryColor} as React.CSSProperties}><span className="market-logo">{marketplace.name.slice(0,2).toUpperCase()}</span><h2 className="serif">{marketplace.name}</h2><p>{marketplace.description}</p><strong>{count} modelo{count===1?'':'s'} →</strong></Link>}
