import Link from 'next/link';
import { ExternalLink, Star } from 'lucide-react';
import type { Currency, ListingBadge, ListingStatus, Marketplace, MarketplaceListing } from '@/types/marketplace';
import { defaultLocale, formatPrice, localizedPath, type Locale } from '@/lib/i18n';

const copy = {
  'pt-br': { status: {'coming-soon':'Em breve','in-production':'Em produção',available:'Disponível','early-access':'Acesso antecipado',exclusive:'Exclusivo',retired:'Retirado',archived:'Arquivado'}, badge: {new:'Novo','best-seller':'Mais vendido',popular:'Popular',featured:'Destaque',exclusive:'Exclusivo','coming-soon':'Em breve'}, buy:'Comprar agora', details:'Ver detalhes', rating:'de 5 estrelas', model:'modelo', models:'modelos' },
  en: { status: {'coming-soon':'Coming Soon','in-production':'In Production',available:'Available','early-access':'Early Access',exclusive:'Exclusive',retired:'Retired',archived:'Archived'}, badge: {new:'New','best-seller':'Best Seller',popular:'Popular',featured:'Featured',exclusive:'Exclusive','coming-soon':'Coming Soon'}, buy:'Buy now', details:'View details', rating:'out of 5 stars', model:'model', models:'models' },
  es: { status: {'coming-soon':'Próximamente','in-production':'En producción',available:'Disponible','early-access':'Acceso anticipado',exclusive:'Exclusivo',retired:'Retirado',archived:'Archivado'}, badge: {new:'Nuevo','best-seller':'Más vendido',popular:'Popular',featured:'Destacado',exclusive:'Exclusivo','coming-soon':'Próximamente'}, buy:'Comprar ahora', details:'Ver detalles', rating:'de 5 estrellas', model:'modelo', models:'modelos' },
} as const satisfies Record<Locale, { status: Record<ListingStatus,string>; badge: Record<ListingBadge,string>; buy:string; details:string; rating:string; model:string; models:string }>;

export function PriceTag({price,currency,locale=defaultLocale}:{price:number;currency:Currency;locale?:Locale}) { return <strong className="market-price">{formatPrice(price,currency,locale)}</strong>; }
export function AvailabilityBadge({status,locale=defaultLocale}:{status:ListingStatus;locale?:Locale}) { return <span className={`availability-badge status-${status}`}>{copy[locale].status[status]}</span>; }
export function MarketplaceBadge({badge,locale=defaultLocale}:{badge:ListingBadge;locale?:Locale}) { return <span className="market-badge">{copy[locale].badge[badge]}</span>; }
export function MarketplaceButton({url,label}:{url:string;label:string}) { return <a className="button" href={url} target="_blank" rel="noopener noreferrer">{label}<ExternalLink size={15}/></a>; }
export function MarketplaceCard({listing,marketplace,locale=defaultLocale}:{listing:MarketplaceListing;marketplace:Marketplace;locale?:Locale}) { const content=copy[locale]; return <article className="market-card" style={{'--market-color':marketplace.primaryColor} as React.CSSProperties}><div className="market-card-head"><span className="market-logo" aria-hidden>{marketplace.name.slice(0,2).toUpperCase()}</span><div><small>DOWNLOAD STL</small><h3 className="serif">{marketplace.name}</h3></div><AvailabilityBadge status={listing.status} locale={locale}/></div><h4>{listing.title}</h4><div className="market-badges">{listing.badges.map(badge=><MarketplaceBadge badge={badge} locale={locale} key={badge}/>)}</div><PriceTag price={listing.price} currency={listing.currency} locale={locale}/>{listing.rating&&<span className="market-rating" aria-label={`${listing.rating} ${content.rating}`}><Star size={14} fill="currentColor"/> {listing.rating.toFixed(1)}</span>}<p className="muted">{listing.notes||listing.license}</p><MarketplaceButton url={listing.url} label={listing.status==='available'||listing.status==='early-access'?content.buy:content.details}/></article>; }
export function MarketplaceGrid({listings,marketplaces,locale=defaultLocale}:{listings:MarketplaceListing[];marketplaces:Marketplace[];locale?:Locale}) { return <div className="market-grid">{listings.map(listing=>{const market=marketplaces.find(item=>item.id===listing.marketplaceId);return market?<MarketplaceCard key={listing.id} listing={listing} marketplace={market} locale={locale}/>:null})}</div>; }
export function MarketplaceList(props:{listings:MarketplaceListing[];marketplaces:Marketplace[];locale?:Locale}) { return <MarketplaceGrid {...props}/>; }
export function MarketplaceHero({title,status='available',locale=defaultLocale}:{title:string;status?:ListingStatus;locale?:Locale}) { return <header className="marketplace-hero"><span className="eyebrow">Marketplace Hub</span><h1 className="serif">{title}</h1><AvailabilityBadge status={status} locale={locale}/></header>; }
export function MarketplaceDirectoryCard({marketplace,count,locale=defaultLocale}:{marketplace:Marketplace;count:number;locale?:Locale}) { const content=copy[locale]; return <Link className="market-directory-card" href={localizedPath(locale,'marketplaces',marketplace.slug)} style={{'--market-color':marketplace.primaryColor} as React.CSSProperties}><span className="market-logo">{marketplace.name.slice(0,2).toUpperCase()}</span><h2 className="serif">{marketplace.name}</h2><p>{marketplace.description}</p><strong>{count} {count===1?content.model:content.models} →</strong></Link>; }
