import {expect,test} from '@playwright/test';
test.describe('localized editorial resolution',()=>{
  for(const [locale,path] of [['pt-br','colecoes'],['en','collections'],['es','colecciones']] as const){
    test(`collection resolves completely in ${locale}`,async({page})=>{await page.goto(`/${locale}/${path}/black-banner-company`);const root=page.locator('.collection-book');await expect(root).toHaveAttribute('data-requested-locale',locale);await expect(root).toHaveAttribute('data-resolved-locale',locale);await expect(root).toHaveAttribute('data-used-fallback','false');await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href',new RegExp(`/${locale}/${path}/black-banner-company$`))});
  }
  test('language switch preserves entity without duplicating locale',async({page})=>{await page.goto('/es/colecciones/black-banner-company');await page.getByLabel('Idioma').selectOption('en');await expect(page).toHaveURL(/\/en\/collections\/black-banner-company$/);await expect(page).not.toHaveURL(/\/en\/en\//)});
  test('character and relations receive the requested locale',async({page})=>{await page.goto('/es/personajes/black-fang-mercenary');const root=page.locator('.character-codex');await expect(root).toHaveAttribute('data-requested-locale','es');await expect(root).toHaveAttribute('data-resolved-locale','es');await expect(root).toHaveAttribute('data-used-fallback','false')});
  test('language switch updates server content without manual reload',async({page})=>{await page.goto('/pt-br/colecoes/black-banner-company');await expect(page.locator('.collection-book')).toHaveAttribute('data-resolved-locale','pt-br');await page.getByLabel('Idioma').selectOption('en');await expect(page).toHaveURL(/\/en\/collections\/black-banner-company$/);await expect(page.locator('.collection-book')).toHaveAttribute('data-resolved-locale','en');await expect(page.locator('.collection-hero').getByText('Veterans, assassins, scouts, and unlikely creatures march beneath a single banner.')).toBeVisible()});
  test('language switch translates static page content together with the header',async({page})=>{await page.goto('/pt-br/universo');await expect(page.getByRole('heading',{name:'Um mundo contado em resina'})).toBeVisible();await page.getByLabel('Idioma').selectOption('en');await expect(page).toHaveURL(/\/en\/universe$/);await expect(page.getByRole('heading',{name:'A world told in resin'})).toBeVisible();await expect(page.getByText('Six crowns preserve the balance. Six guardians pay its price.')).toBeVisible();await expect(page.getByRole('navigation',{name:'Main navigation'})).toBeVisible()});
});
