'use client';
import Image from 'next/image';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {Compass,Filter,Map,Minus,Plus,RotateCcw,X} from 'lucide-react';
import {useMemo,useRef,useState} from 'react';
import {atlasEras,atlasFeatures,atlasLayerLabels,atlasLines,atlasModeLabels,atlasModeLayers,atlasPoints,atlasRealms,type AtlasFeature,type AtlasFilter,type AtlasLayer,type AtlasMode} from '@/data/atlas';
import {isLocale,localizedPath,type Locale} from '@/lib/i18n';
import {RealmSigil} from './RealmSigil';

const filterLabels:Record<AtlasFilter,string>={realms:'Reinos',guardians:'Guardiões',crowns:'Coroas',characters:'Personagens',collections:'Coleções',marketplace:'Marketplace',creatures:'Criaturas',bosses:'Bosses',locations:'Locais'};
const initialFilters=new Set<AtlasFilter>(['realms','guardians','crowns','creatures','bosses','locations']);
const layerSymbol:Record<AtlasLayer,string>={routes:'↝',rivers:'≈',mountains:'▲',fortresses:'◆',ruins:'⌁',ports:'⚓',forests:'♠',mines:'◇',forges:'✦',capitals:'★',pois:'•'};
export function AsterheimMap(){return <AsterheimAtlas mode="compact"/>}

export function AsterheimAtlas({mode='full'}:{mode?:'compact'|'full'}){
  const pathname=usePathname(),first=pathname.split('/').filter(Boolean)[0],locale:Locale=isLocale(first)?first:'pt-br';
  const [selected,setSelected]=useState(atlasRealms[0]),[point,setPoint]=useState<(typeof atlasPoints)[number]>(),[feature,setFeature]=useState<AtlasFeature>(),[eraIndex,setEraIndex]=useState(3),[filters,setFilters]=useState(initialFilters),[mapMode,setMapMode]=useState<AtlasMode>('physical'),[layers,setLayers]=useState<Set<AtlasLayer>>(()=>new Set(atlasModeLayers.physical)),[scale,setScale]=useState(mode==='full'?1.04:1),[pan,setPan]=useState({x:0,y:0});
  const drag=useRef<{x:number;y:number;panX:number;panY:number}|undefined>(undefined);
  const visiblePoints=useMemo(()=>atlasPoints.filter(item=>item.realm===selected.slug&&filters.has(item.category)),[selected,filters]);
  const visibleFeatures=useMemo(()=>atlasFeatures.filter(item=>layers.has(item.layer)&&(item.realm===selected.slug||item.layer==='capitals')),[layers,selected.slug]);
  const visibleLines=useMemo(()=>atlasLines.filter(line=>layers.has(line.layer)&&(!line.era||line.era===atlasEras[eraIndex].id)),[layers,eraIndex]);
  const focusScale=mode==='compact'?1.14:scale,focusX=(50-selected.x)*(focusScale-1)*1.45,focusY=(50-selected.y)*(focusScale-1)*1.15;
  function selectRealm(realm:(typeof atlasRealms)[number]){setSelected(realm);setPoint(undefined);setFeature(undefined)}
  function toggleFilter(filter:AtlasFilter){setFilters(current=>{const next=new Set(current);if(next.has(filter))next.delete(filter);else next.add(filter);return next})}
  function toggleLayer(layer:AtlasLayer){setLayers(current=>{const next=new Set(current);if(next.has(layer))next.delete(layer);else next.add(layer);return next})}
  function changeMode(next:AtlasMode){setMapMode(next);setLayers(new Set(atlasModeLayers[next]));setFeature(undefined)}
  function reset(){setScale(mode==='full'?1.04:1);setPan({x:0,y:0});setPoint(undefined);setFeature(undefined);selectRealm(atlasRealms[0])}
  return <section className={`asterheim-atlas ${mode}`} aria-label="Mapa ilustrado interativo de Asterheim" data-era={atlasEras[eraIndex].id} data-mode={mapMode}>
    {mode==='full'?<><header className="atlas-toolbar"><div><span className="eyebrow">Cartografia viva · edição profissional</span><h1 className="serif">Atlas de Asterheim</h1></div><div className="atlas-zoom"><button onClick={()=>setScale(value=>Math.max(1,value-.18))} aria-label="Reduzir zoom"><Minus/></button><span>{Math.round(scale*100)}%</span><button onClick={()=>setScale(value=>Math.min(2.4,value+.18))} aria-label="Ampliar mapa"><Plus/></button><button onClick={reset} aria-label="Redefinir mapa"><RotateCcw/></button></div></header><nav className="atlas-mode-nav" aria-label="Tipo de mapa">{(Object.keys(atlasModeLabels) as AtlasMode[]).map(item=><button key={item} aria-pressed={mapMode===item} onClick={()=>changeMode(item)}>{atlasModeLabels[item]}</button>)}</nav><aside className="atlas-filters"><span><Filter/> Camadas</span><div className="atlas-filter-group"><small>Cartografia</small>{(Object.keys(atlasLayerLabels) as AtlasLayer[]).map(layer=><button key={layer} className={layers.has(layer)?'active':''} onClick={()=>toggleLayer(layer)} aria-label={atlasLayerLabels[layer]} aria-pressed={layers.has(layer)}><i aria-hidden="true">{layerSymbol[layer]}</i>{atlasLayerLabels[layer]}</button>)}</div><div className="atlas-filter-group secondary"><small>Registros</small>{(Object.keys(filterLabels) as AtlasFilter[]).map(filter=><button key={filter} className={filters.has(filter)?'active':''} onClick={()=>toggleFilter(filter)} aria-pressed={filters.has(filter)}>{filterLabels[filter]}</button>)}</div></aside></>:null}
    <div className="atlas-viewport" onWheel={mode==='full'?event=>{event.preventDefault();setScale(value=>Math.min(2.4,Math.max(1,value+(event.deltaY<0?.12:-.12))))}:undefined} onPointerDown={mode==='full'?event=>{if((event.target as Element).closest('button,a,[role="button"]'))return;drag.current={x:event.clientX,y:event.clientY,panX:pan.x,panY:pan.y};event.currentTarget.setPointerCapture(event.pointerId)}:undefined} onPointerMove={mode==='full'?event=>{if(drag.current)setPan({x:drag.current.panX+event.clientX-drag.current.x,y:drag.current.panY+event.clientY-drag.current.y})}:undefined} onPointerUp={mode==='full'?()=>{drag.current=undefined}:undefined}>
      <div className="atlas-canvas" style={{transform:`translate3d(${pan.x+focusX}px,${pan.y+focusY}px,0) scale(${focusScale})`}}>
        <Image src="/images/atlas/asterheim-atlas-v1.webp" alt="Mapa físico e político do continente de Asterheim" fill priority={mode==='full'} sizes={mode==='full'?'100vw':'(max-width: 900px) 100vw, 1200px'} draggable={false}/>
        <div className={`atlas-weather ${selected.weather}`} aria-hidden="true"/>
        <svg className="atlas-regions" viewBox="0 0 100 100" role="group" aria-label="Fronteiras dos seis reinos">{atlasRealms.map(realm=><path key={realm.slug} d={realm.path} className={selected.slug===realm.slug?'selected':''} style={{'--realm':realm.accent} as React.CSSProperties} onClick={()=>selectRealm(realm)} role="button" tabIndex={0} aria-label={`Explorar ${realm.name}`} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();selectRealm(realm)}}}/>)}</svg>
        <svg className="atlas-network" viewBox="0 0 100 100" aria-label="Rotas e rios">{visibleLines.map(line=><path key={line.id} d={line.d} className={line.layer}><title>{line.label}</title></path>)}</svg>
        {filters.has('realms')?atlasRealms.map(realm=><button className={`atlas-sigil ${selected.slug===realm.slug?'selected':''}`} style={{left:`${realm.x}%`,top:`${realm.y}%`,'--realm':realm.accent} as React.CSSProperties} key={realm.slug} onClick={()=>selectRealm(realm)} aria-label={`${realm.name}: ${realm.symbol}`}><RealmSigil realm={realm.slug}/><span>{realm.name}</span></button>):null}
        {visibleFeatures.map(item=><button key={item.id} className={`atlas-feature layer-${item.layer}`} style={{left:`${item.x}%`,top:`${item.y}%`} as React.CSSProperties} onClick={()=>{setFeature(item);setPoint(undefined)}} aria-label={`${atlasLayerLabels[item.layer]}: ${item.label}`}><i>{layerSymbol[item.layer]}</i><span>{item.label}</span></button>)}
        {visiblePoints.map(item=><button key={`${item.realm}-${item.slug}`} className={`atlas-poi ${item.danger?'danger':''}`} style={{left:`${item.x}%`,top:`${item.y}%`} as React.CSSProperties} onClick={()=>{setPoint(item);setFeature(undefined)}} aria-label={`${item.kind}: ${item.name}`}><i/><span>{item.name}</span></button>)}
      </div><div className="atlas-vignette" aria-hidden="true"/>{mode==='full'?<div className="atlas-compass" aria-hidden="true"><Compass/><span>N</span></div>:null}
    </div>
    <aside className="atlas-detail" style={{'--realm':selected.accent} as React.CSSProperties}><RealmSigil realm={selected.slug}/><div><span className="eyebrow">{atlasModeLabels[mapMode]} · {selected.symbol}</span><h2 className="serif">{selected.name}</h2><p>{selected.summary}</p><p><strong>Arquitetura</strong>{selected.architecture}</p><div className="atlas-actions"><Link className="button" href={localizedPath(locale,'realms',selected.slug)}>Abrir Reino</Link>{mode==='compact'?<Link className="button ghost" href={localizedPath(locale,'atlas')}>Abrir Atlas</Link>:null}</div></div></aside>
    {point?<aside className="atlas-point-card" style={{'--realm':selected.accent} as React.CSSProperties}><button className="atlas-close" onClick={()=>setPoint(undefined)} aria-label="Fechar ponto"><X/></button><small>{point.kind} · {selected.name}</small><h2 className="serif">{point.name}</h2><p>{point.description}</p>{point.related?.length?<p><strong>Conexões</strong>{point.related.join(' · ')}</p>:null}<Link className="button" href={localizedPath(locale,'atlas',`${point.realm}/${point.slug}`)}>Abrir registro</Link></aside>:null}
    {feature?<aside className="atlas-point-card atlas-feature-card" style={{'--realm':selected.accent} as React.CSSProperties}><button className="atlas-close" onClick={()=>setFeature(undefined)} aria-label="Fechar anotação"><X/></button><small>{atlasLayerLabels[feature.layer]} · camada derivada</small><h2 className="serif">{feature.label}</h2><p>{feature.description}</p><span className="atlas-derived-badge">Não altera o Canon</span></aside>:null}
    {mode==='full'?<><footer className="atlas-timeline"><div><small>{atlasEras[eraIndex].year}</small><strong>{atlasEras[eraIndex].label}</strong><p>{atlasEras[eraIndex].description}</p></div><input type="range" min="0" max={atlasEras.length-1} value={eraIndex} onChange={event=>setEraIndex(Number(event.target.value))} aria-label="Era exibida no mapa"/><div className="atlas-era-labels">{atlasEras.map(era=><span key={era.id}>{era.label}</span>)}</div></footer><div className="atlas-minimap"><Map/><div><i style={{left:`${selected.x}%`,top:`${selected.y}%`}}/></div><span>Visão continental</span></div></>:null}
  </section>
}
