import Image from 'next/image';
import Link from 'next/link';
import { AlertTriangle, CheckCircle2, MapPin, Printer, ShieldAlert, Sparkles } from 'lucide-react';
import type { CSSProperties } from 'react';
import { atlasPoints } from '@/data/atlas';
import { creatureRealmProfiles } from '@/data/creatures';
import { selectPublicCreatureGlb, selectPublicCreatureImage } from '@/lib/creature-assets';
import { creatureCategoryLabel, creatureProductionLabel, creatureThreatLabel } from '@/lib/creature-display';
import { localizedPath, type Locale } from '@/lib/i18n';
import type { LocalizedCreature } from '@/types/creature';
import { Creature3DViewer } from './Creature3DViewer';
import { CreatureGallery } from './CreatureGallery';

const copy = {
  'pt-br': { origin: 'Origem e registro', behavior: 'Comportamento', habitat: 'Habitat e avistamentos', diet: 'Dieta', abilities: 'Habilidades', weaknesses: 'Fraquezas conhecidas', threat: 'Nível de ameaça', technical: 'Miniatura oficial', source: 'Estado da produção', private: 'Arquivos mestres preservados fora da área pública.', unverified: 'Escala, suportes e impressão física ainda não validados.', market: 'Marketplace', coming: 'Em produção; nenhum anúncio público foi vinculado.', back: 'Voltar às criaturas', viewer: 'Inspeção 3D', load: 'Carregar modelo 3D', unavailable: 'Modelo 3D em preparação', unavailableText: 'O arquivo web otimizado ainda não foi publicado. Acompanhe o processo de produção.', process: 'Ver processo de produção', reset: 'Reiniciar', fullscreen: 'Tela cheia', clay: 'Argila', painted: 'Pintado', wireframe: 'Malha', loading: 'Carregando', relations: 'Relações no mundo', related: 'Registros relacionados', gallery: 'Galeria de campo', empty: 'Novos registros visuais ainda não foram publicados.', open: 'Ampliar imagem', close: 'Fechar', previous: 'Anterior', next: 'Próxima', yes: 'Sim', no: 'Não', included: 'Incluída', pending: 'Pendente' },
  en: { origin: 'Origin and record', behavior: 'Behavior', habitat: 'Habitat and sightings', diet: 'Diet', abilities: 'Abilities', weaknesses: 'Known weaknesses', threat: 'Threat level', technical: 'Official miniature', source: 'Production status', private: 'Master files are preserved outside the public area.', unverified: 'Scale, supports, and physical printing are not validated yet.', market: 'Marketplace', coming: 'In production; no public listing is linked.', back: 'Back to creatures', viewer: '3D inspection', load: 'Load 3D model', unavailable: '3D model in preparation', unavailableText: 'The optimized web file has not been published. Follow the production process.', process: 'View production process', reset: 'Reset', fullscreen: 'Fullscreen', clay: 'Clay', painted: 'Painted', wireframe: 'Wireframe', loading: 'Loading', relations: 'World relations', related: 'Related records', gallery: 'Field gallery', empty: 'No additional visual records have been published.', open: 'Enlarge image', close: 'Close', previous: 'Previous', next: 'Next', yes: 'Yes', no: 'No', included: 'Included', pending: 'Pending' },
  es: { origin: 'Origen y registro', behavior: 'Comportamiento', habitat: 'Hábitat y avistamientos', diet: 'Dieta', abilities: 'Habilidades', weaknesses: 'Debilidades conocidas', threat: 'Nivel de amenaza', technical: 'Miniatura oficial', source: 'Estado de producción', private: 'Los archivos maestros se conservan fuera del área pública.', unverified: 'Escala, soportes e impresión física aún no están validados.', market: 'Marketplace', coming: 'En producción; no hay anuncio público vinculado.', back: 'Volver a criaturas', viewer: 'Inspección 3D', load: 'Cargar modelo 3D', unavailable: 'Modelo 3D en preparación', unavailableText: 'El archivo web optimizado aún no fue publicado. Sigue el proceso de producción.', process: 'Ver proceso de producción', reset: 'Reiniciar', fullscreen: 'Pantalla completa', clay: 'Arcilla', painted: 'Pintado', wireframe: 'Malla', loading: 'Cargando', relations: 'Relaciones del mundo', related: 'Registros relacionados', gallery: 'Galería de campo', empty: 'Aún no se publicaron registros visuales adicionales.', open: 'Ampliar imagen', close: 'Cerrar', previous: 'Anterior', next: 'Siguiente', yes: 'Sí', no: 'No', included: 'Incluida', pending: 'Pendiente' },
} as const;

export function CreatureRecord({ creature, related, locale }: { creature: LocalizedCreature; related: LocalizedCreature[]; locale: Locale }) {
  const ui = copy[locale], realm = creatureRealmProfiles[creature.realmId as keyof typeof creatureRealmProfiles];
  const image = selectPublicCreatureImage(creature), model = selectPublicCreatureGlb(creature);
  const habitatPoints = creature.habitats.map((habitat) => atlasPoints.find((point) => `${point.realm}/${point.slug}` === habitat.locationId)).filter((point): point is NonNullable<typeof point> => Boolean(point));
  return <article className="creature-record" style={{ '--creature-accent': realm.palette[2], '--creature-deep': realm.palette[0] } as CSSProperties}>
    <header className="creature-record-hero"><Image src={image} alt={creature.imageAlt} fill priority sizes="100vw"/><div className="creature-record-shade"/><div className="container"><Link href={localizedPath(locale, 'atlas', 'creatures')} className="creature-back">← {ui.back}</Link><span className="eyebrow">{realm.name} · {creatureCategoryLabel(locale, creature.category)}</span><h1>{creature.name}</h1><p className="creature-record-epithet">{creature.epithet}</p><p className="lead">{creature.summary}</p><div className="creature-hero-facts"><span><ShieldAlert/>{ui.threat}: <strong>{creatureThreatLabel(locale, creature.threatLevel)}</strong></span><span><MapPin/>{creature.habitat}</span></div></div></header>
    <div className="creature-record-flow">
      <section className="creature-lore container"><div><span className="eyebrow">{ui.origin}</span><h2>{creature.epithet}</h2><p className="creature-dropcap">{creature.lore}</p><p>{creature.origin}</p><p>{creature.historicalRecord}</p></div><blockquote>“{creature.relationToRealm}”</blockquote></section>
      <section className="creature-split container"><div className="creature-panel"><Sparkles/><span className="eyebrow">{ui.behavior}</span><h2>{ui.behavior}</h2><p>{creature.behavior}</p><h3>{ui.diet}</h3><p>{creature.diet}</p></div><div className="creature-panel creature-habitat"><MapPin/><span className="eyebrow">{ui.habitat}</span><h2>{realm.name}</h2><p>{creature.habitat}</p>{creature.habitats.map((place) => <p className="creature-sighting" key={place.locationId}><strong>{place.kind}</strong> · {place.rarity}<br/>{place.notes}</p>)}</div></section>
      <section className="creature-habitat-map container" aria-label={ui.habitat}><div><Image src="/images/atlas/asterheim-atlas-v1.webp" alt="" fill sizes="(max-width: 900px) 100vw, 1200px"/>{habitatPoints.map((point) => <Link key={point.slug} href={localizedPath(locale, 'atlas', `${point.realm}/${point.slug}`)} style={{ left: `${point.x}%`, top: `${point.y}%` }} aria-label={point.name}><span/></Link>)}</div></section>
      <section className="creature-traits container"><div><h2>{ui.abilities}</h2><ul>{creature.abilities.map((ability) => <li key={ability}><CheckCircle2/>{ability}</li>)}</ul></div><div><h2>{ui.weaknesses}</h2><ul>{creature.weaknesses.map((weakness) => <li key={weakness}><AlertTriangle/>{weakness}</li>)}</ul></div></section>
      <CreatureGallery items={creature.gallery} alt={creature.imageAlt} captions={creature.captions} labels={{ title: ui.gallery, empty: ui.empty, open: ui.open, close: ui.close, previous: ui.previous, next: ui.next }}/>
      {model ? <div className="container"><Creature3DViewer name={creature.name} modelUrl={model} fallbackImage={image} labels={{ title: ui.viewer, load: ui.load, unavailable: ui.unavailable, slow: ui.unavailableText, reset: ui.reset, fullscreen: ui.fullscreen, clay: ui.clay, painted: ui.painted, wireframe: ui.wireframe, loading: ui.loading }}/></div> : <section className="container creature-model-pending"><span className="eyebrow">{ui.viewer}</span><h2>{ui.unavailable}</h2><p>{ui.unavailableText}</p><Link className="button ghost" href={localizedPath(locale, 'print')}>{ui.process}</Link></section>}
      <section className="creature-technical container"><div><Printer/><span className="eyebrow">{ui.technical}</span><h2>{ui.source}</h2><p>{creatureProductionLabel(locale, creature.productionStatus)}</p><p>{ui.private}</p><p>{ui.unverified}</p></div><dl><div><dt>STL</dt><dd>{creature.stlSourceAvailable ? ui.yes : ui.no}</dd></div><div><dt>GLB web</dt><dd>{model ? ui.yes : ui.pending}</dd></div><div><dt>Multipart</dt><dd>{creature.technical.multipart ? ui.yes : ui.no}</dd></div><div><dt>Base</dt><dd>{creature.technical.baseIncluded ? ui.included : ui.pending}</dd></div></dl></section>
      <section className="container creature-market"><span className="eyebrow">{ui.market}</span><h2>Creality Cloud</h2><p>{ui.coming}</p><span className="status-pill">{creatureProductionLabel(locale, creature.productionStatus)}</span></section>
      <section className="container creature-relations"><span className="eyebrow">{ui.relations}</span><div className="creature-relation-grid"><Link href={localizedPath(locale, 'realms', creature.realmId)}>{realm.name}</Link><Link href={localizedPath(locale, 'guardians', creature.guardianId)}>{creature.guardianId}</Link><Link href={localizedPath(locale, 'crowns', creature.crownId)}>{creature.crownId}</Link></div></section>
      <section className="container creature-related"><span className="eyebrow">{ui.related}</span><div>{related.map((item) => <Link href={localizedPath(locale, 'atlas', `creatures/${item.slug}`)} key={item.slug}><Image src={item.thumbnail} alt="" width={160} height={160}/><span><strong>{item.name}</strong><small>{item.epithet} · {creatureThreatLabel(locale, item.threatLevel)}</small></span></Link>)}</div></section>
    </div>
  </article>;
}
