import Image from 'next/image';
import Link from 'next/link';
import { AlertTriangle, Box, CheckCircle2, MapPin, Printer, ShieldAlert, Sparkles } from 'lucide-react';
import type { CSSProperties } from 'react';
import { creatureRealmProfiles } from '@/data/creatures';
import { atlasPoints } from '@/data/atlas';
import { selectPublicCreatureGlb, selectPublicCreatureImage } from '@/lib/creature-assets';
import { localizedPath, type Locale } from '@/lib/i18n';
import type { LocalizedCreature } from '@/types/creature';
import { Creature3DViewer } from './Creature3DViewer';

const copy = {
  'pt-br': { atlas: 'Atlas das Criaturas', origin: 'Origem', behavior: 'Comportamento', habitat: 'Habitat e avistamentos', diet: 'Dieta', abilities: 'Habilidades', weaknesses: 'Fraquezas conhecidas', threat: 'Nível de ameaça', technical: 'Arquivo para miniatura', process: 'Processo criativo', prompt: 'Prompt oficial', relations: 'Relações no mundo', related: 'Outras criaturas deste Reino', source: 'Disponibilidade técnica', stl: 'STL mestre localizado', glb: 'GLB mestre localizado', private: 'Masters preservados fora da área pública', unverified: 'Escala, suportes e impressão física ainda não validados.', market: 'Marketplace', coming: 'Em produção; nenhum anúncio público foi vinculado.', back: 'Voltar às criaturas', viewer: 'Inspeção 3D', load: 'Carregar modelo 3D', unavailable: 'Modelo web otimizado ainda não publicado.', slow: 'Conexão econômica detectada. O modelo só será baixado ao confirmar.', reset: 'Reiniciar', fullscreen: 'Tela cheia', clay: 'Argila', painted: 'Pintado', wireframe: 'Malha', loading: 'Carregando' },
  en: { atlas: 'Creature Atlas', origin: 'Origin', behavior: 'Behavior', habitat: 'Habitat and sightings', diet: 'Diet', abilities: 'Abilities', weaknesses: 'Known weaknesses', threat: 'Threat level', technical: 'Miniature file', process: 'Creative process', prompt: 'Official prompt', relations: 'World relations', related: 'More creatures from this Realm', source: 'Technical availability', stl: 'Master STL located', glb: 'Master GLB located', private: 'Masters preserved outside the public area', unverified: 'Scale, supports, and physical printing are not validated yet.', market: 'Marketplace', coming: 'In production; no public listing is linked.', back: 'Back to creatures', viewer: '3D inspection', load: 'Load 3D model', unavailable: 'Optimized web model is not published yet.', slow: 'Data-saving connection detected. The model downloads only after confirmation.', reset: 'Reset', fullscreen: 'Fullscreen', clay: 'Clay', painted: 'Painted', wireframe: 'Wireframe', loading: 'Loading' },
  es: { atlas: 'Atlas de Criaturas', origin: 'Origen', behavior: 'Comportamiento', habitat: 'Hábitat y avistamientos', diet: 'Dieta', abilities: 'Habilidades', weaknesses: 'Debilidades conocidas', threat: 'Nivel de amenaza', technical: 'Archivo de miniatura', process: 'Proceso creativo', prompt: 'Prompt oficial', relations: 'Relaciones del mundo', related: 'Otras criaturas de este Reino', source: 'Disponibilidad técnica', stl: 'STL maestro localizado', glb: 'GLB maestro localizado', private: 'Masters preservados fuera del área pública', unverified: 'Escala, soportes e impresión física aún no están validados.', market: 'Marketplace', coming: 'En producción; no hay anuncio público vinculado.', back: 'Volver a criaturas', viewer: 'Inspección 3D', load: 'Cargar modelo 3D', unavailable: 'El modelo web optimizado aún no está publicado.', slow: 'Conexión de ahorro detectada. El modelo solo se descarga al confirmar.', reset: 'Reiniciar', fullscreen: 'Pantalla completa', clay: 'Arcilla', painted: 'Pintado', wireframe: 'Malla', loading: 'Cargando' },
} as const;

export function CreatureRecord({ creature, related, locale }: { creature: LocalizedCreature; related: LocalizedCreature[]; locale: Locale }) {
  const ui = copy[locale], realm = creatureRealmProfiles[creature.realmId as keyof typeof creatureRealmProfiles];
  const image = selectPublicCreatureImage(creature) || creature.image, model = selectPublicCreatureGlb(creature);
  const galleryLabel = locale === 'en' ? 'Field gallery' : locale === 'es' ? 'Galería de campo' : 'Galeria de campo';
  const habitatPoints = creature.habitats.map((habitat) => atlasPoints.find((point) => `${point.realm}/${point.slug}` === habitat.locationId)).filter((point): point is NonNullable<typeof point> => Boolean(point));
  return <article className="creature-record" style={{ '--creature-accent': realm.palette[2], '--creature-deep': realm.palette[0] } as CSSProperties}>
    <header className="creature-record-hero"><Image src={image} alt={creature.imageAlt} fill priority sizes="100vw"/><div className="creature-record-shade"/><div className="container"><Link href={localizedPath(locale, 'atlas', 'creatures')} className="creature-back">← {ui.back}</Link><span className="eyebrow">{realm.name} · {creature.category}</span><h1>{creature.name}</h1><p className="creature-record-epithet">{creature.epithet}</p><p className="lead">{creature.summary}</p><div className="creature-hero-facts"><span><ShieldAlert/>{ui.threat}: <strong>{creature.threatLevel}</strong></span><span><MapPin/>{creature.habitat}</span></div></div></header>
    <div className="creature-record-flow">
      <section className="creature-lore container"><div><span className="eyebrow">{ui.origin}</span><h2>{creature.epithet}</h2><p className="creature-dropcap">{creature.lore}</p><p>{creature.origin}</p></div><blockquote>“{creature.summary}”</blockquote></section>
      <section className="creature-split container"><div className="creature-panel"><Sparkles/><span className="eyebrow">{ui.behavior}</span><h2>{ui.behavior}</h2><p>{creature.behavior}</p><h3>{ui.diet}</h3><p>{creature.diet}</p></div><div className="creature-panel creature-habitat"><MapPin/><span className="eyebrow">{ui.habitat}</span><h2>{realm.name}</h2><p>{creature.habitat}</p>{creature.habitats.map((place) => <p className="creature-sighting" key={place.locationId}><strong>{place.kind}</strong> · {place.rarity}<br/>{place.notes}</p>)}</div></section>
      <section className="creature-habitat-map container" aria-label={ui.habitat}><div><Image src="/images/atlas/asterheim-atlas-v1.webp" alt="" fill sizes="(max-width: 900px) 100vw, 1200px"/>{habitatPoints.map((point) => <Link key={point.slug} href={localizedPath(locale, 'atlas', `${point.realm}/${point.slug}`)} style={{ left: `${point.x}%`, top: `${point.y}%` }} aria-label={`${point.name}: ${point.kind}`}><span/></Link>)}</div><ul>{habitatPoints.map((point) => <li key={point.slug}><Link href={localizedPath(locale, 'atlas', `${point.realm}/${point.slug}`)}><strong>{point.name}</strong><small>{point.kind} · {point.danger ? 'danger zone' : 'habitat'}</small></Link></li>)}</ul></section>
      <section className="creature-traits container"><div><h2>{ui.abilities}</h2><ul>{creature.abilities.map((ability) => <li key={ability}><CheckCircle2/>{ability}</li>)}</ul></div><div><h2>{ui.weaknesses}</h2><ul>{creature.weaknesses.map((weakness) => <li key={weakness}><AlertTriangle/>{weakness}</li>)}</ul></div></section>
      <section className="creature-gallery container"><span className="eyebrow">{galleryLabel}</span><div>{creature.captions.map((caption, index) => <figure key={caption}><div><Image src={image} alt={index === 0 ? creature.imageAlt : ''} fill sizes="(max-width: 700px) 100vw, 50vw"/></div><figcaption>{caption}</figcaption></figure>)}</div></section>
      <div className="container"><Creature3DViewer name={creature.name} modelUrl={model} fallbackImage={image} labels={{ title: ui.viewer, load: ui.load, unavailable: ui.unavailable, slow: ui.slow, reset: ui.reset, fullscreen: ui.fullscreen, clay: ui.clay, painted: ui.painted, wireframe: ui.wireframe, loading: ui.loading }}/></div>
      <section className="creature-technical container"><div><Printer/><span className="eyebrow">{ui.technical}</span><h2>{ui.source}</h2><ul><li>{creature.stlSourceAvailable ? '✓' : '—'} {ui.stl}</li><li>{creature.glbSourceAvailable ? '✓' : '—'} {ui.glb}</li><li>{ui.private}</li></ul><p>{ui.unverified}</p></div><dl><div><dt>Print status</dt><dd>{creature.technical.printStatus}</dd></div><div><dt>Supports</dt><dd>{creature.technical.supportStatus}</dd></div><div><dt>Multipart</dt><dd>{creature.technical.multipart ? 'Yes' : 'No'}</dd></div><div><dt>Base</dt><dd>{creature.technical.baseIncluded ? 'Included' : 'Pending'}</dd></div></dl></section>
      <section className="creature-process container"><div><Box/><span className="eyebrow">{ui.process}</span><h2>{ui.prompt}</h2><p>{creature.visualDirection}</p><details><summary>{ui.prompt}</summary><p>{creature.prompt}</p></details></div><div className="creature-market"><span className="eyebrow">{ui.market}</span><h2>Creality Cloud</h2><p>{ui.coming}</p><span className="status-pill">{creature.marketplace[0]?.availability}</span></div></section>
      <section className="container creature-relations"><span className="eyebrow">{ui.relations}</span><div className="creature-relation-grid"><Link href={localizedPath(locale, 'realms', creature.realmId)}>Realm · {realm.name}</Link><Link href={localizedPath(locale, 'guardians', creature.guardianId)}>Guardian · {creature.guardianId}</Link><Link href={localizedPath(locale, 'crowns', creature.crownId)}>Crown · {creature.crownId}</Link></div></section>
      <section className="container creature-related"><span className="eyebrow">{ui.related}</span><div>{related.map((item) => <Link href={localizedPath(locale, 'atlas', `creatures/${item.slug}`)} key={item.slug}><Image src={item.image} alt="" width={160} height={160}/><span><strong>{item.name}</strong><small>{item.epithet}</small></span></Link>)}</div></section>
    </div>
  </article>;
}
